name: Publish Backend Docker image for Ethrex

on:
  workflow_dispatch:
  push:
    branches:
      - ethrex-explorer
    paths-ignore:
      - 'CHANGELOG.md'
      - '**/README.md'

env:
  RELEASE_VERSION: 9.2.2

permissions:
  contents: read
  packages: write

jobs:
  push_backend_to_registry:
    name: Push Backend Docker image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/lambdaclass/backend-private:buildcache
          cache-to: type=registry,ref=ghcr.io/lambdaclass/backend-private:buildcache,mode=max
          tags: |
            ghcr.io/damiramirez/backend:ethrex
            ghcr.io/damiramirez/backend:ethrex-${{ env.SHORT_SHA }}
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}.ethrex.${{ env.SHORT_SHA }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
